apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: owner-rb
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  name: owner-role
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io