apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: owner-role
rules:
  - apiGroups: ["*"]
    resources: ["daemonsets"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["*"]
    resources: ["statefulsets"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["*"]
    resources: ["replicasets"]
    verbs: ["list", "get", "watch"]
  - apiGroups: [ "*" ]
    resources: [ "jobs" ]
    verbs: [ "list", "get", "watch" ]
  - apiGroups: [ "*" ]
    resources: [ "cronjobs" ]
    verbs: [ "list", "get", "watch" ]
  - apiGroups: ["*"]
    resources: ["deployments"]
    verbs: ["list", "get", "watch"]